INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Clarke', 'Griffin', 'clarke@test.com', '$2a$10$WFNsDxUo/Pu9kQBto2GDC.731bJovSBfspwrZmtgAuSFHqTz1VYnq');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Raven', 'Rayes', 'raven@test.com', '$2a$10$WFNsDxUo/Pu9kQBto2GDC.731bJovSBfspwrZmtgAuSFHqTz1VYnq');

INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);


INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jogos', NOW());

INSERT INTO tb_product (name, price, date, description, img_url, rate_average, rate_quantity) VALUES ('Amor & Gelato', 24.90, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z', 'Um verão na Itália, uma antiga história de amor e um segredo de família. Depois da morte da mãe, Lina fica com a missão de realizar um último pedido: ir até a Itália para conhecer o pai. Do dia para a noite, ela se vê na famosa paisagem da Toscana, morando em uma casa localizada no mesmo terreno de um cemitério memorial de soldados americanos da Segunda Guerra Mundial, com um homem que nunca tinha ouvido falar. Apesar das belezas arquitetônicas, da história da cidade e das comidas maravilhosas, o que Lina mais quer é ir embora correndo dali. Mas as coisas começam a mudar quando ela recebe um antigo diário da mãe. Nele, a menina embarca em uma misteriosa história de amor, que pode explicar suas próprias origens. No meio desse turbilhão de emoções, Lina ainda conhece Ren e Thomas, dois meninos lindos que vão mexer ainda mais com seu coração. Uma trajetória que fará Lina descobrir o amor, a si mesma e também aprender a lidar com a perda. Amor & gelato é uma deliciosa viagem pelos mais românticos pontos turísticos italianos, com direito a tudo de mais intenso que o lugar tem a oferecer: desde paixões até corações partidos.', 'https://images-na.ssl-images-amazon.com/images/I/51NBI1de8hL._SX331_BO1,204,203,200_.jpg', 10, 7);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average, rate_quantity) VALUES ('Teto Para Dois', 37.40, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Três meses após o término do seu relacionamento, Tiffy finalmente sai do apartamento do ex-namorado. Agora ela precisa para ontem de um lugar barato para morar. Contrariando os amigos, ela topa um acordo bastante inusitado. Leon está enrolado com questões financeiras e tem uma ideia pouco convencional para arranjar dinheiro rápido: sublocar seu apartamento, onde fica apenas no período da manhã e da tarde nos dias úteis, já que passa os finais de semana com a namorada e trabalha como enfermeiro no turno da noite. Só que tem um detalhe importante: o lugar tem apenas uma cama. Sem nunca terem se encontrado pessoalmente, Leon e Tiffy fecham um contrato de seis meses e passam a resolver as trivialidades do dia a dia por Post-its espalhados pela casa. Mas será que essa solução aparentemente perfeita resiste a um ex-namorado obsessivo, uma namorada ciumenta, um irmão encrencado, dois empregos exigentes e alguns amigos superprotetores?', 'https://images-na.ssl-images-amazon.com/images/I/51YxURViIqL._SX295_BO1,204,203,200_.jpg', 9.9, 1293);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average, rate_quantity) VALUES ('Por lugares incríveis', 27.99, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Violet Markey tinha uma vida perfeita, mas todos os seus planos deixam de fazer sentido quando ela e a irmã sofrem um acidente de carro e apenas Violet sobrevive. Sentindo-se culpada pelo que aconteceu, a garota se afasta de todos e tenta descobrir como seguir em frente. Theodore Finch é o esquisito da escola, perseguido pelos valentões e chamado de “aberração” por onde passa. Para piorar, é obrigado a lidar com longos períodos de depressão, o pai violento e a apatia do resto da família. Enquanto Violet conta os dias para o fim das aulas, quando poderá ir embora da cidadezinha onde mora, Finch pesquisa diferentes métodos de suicídio e imagina se conseguiria levar algum deles adiante. Em uma dessas tentativas, ele vai parar no alto da torre da escola e, para sua surpresa, encontra Violet, também prestes a pular. Um ajuda o outro a sair dali, e essa dupla improvável se une para fazer um trabalho de geografia: conhecer lugares incríveis do estado onde moram. Ao lado de Finch, Violet para de contar os dias e finalmente passa a vivê-los. O garoto, por sua vez, encontra alguém com quem pode ser ele mesmo, e torce para que consiga se manter desperto.', 'https://images-na.ssl-images-amazon.com/images/I/510HCDDGb3L._SX331_BO1,204,203,200_.jpg', 5, 1);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average, rate_quantity) VALUES ('A rainha vermelha', 24.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses. Mare rouba o que pode para ajudar sua família a sobreviver e não tem esperanças de escapar do vilarejo miserável onde mora. Entretanto, numa reviravolta do destino, ela consegue um emprego no palácio real, onde, em frente ao rei e a toda a nobreza, descobre que tem um poder misterioso… Mas como isso seria possível, se seu sangue é vermelho? Em meio às intrigas dos nobres prateados, as ações da garota vão desencadear uma dança violenta e fatal, que colocará príncipe contra príncipe - e Mare contra seu próprio coração.', 'https://images-na.ssl-images-amazon.com/images/I/41-+BzOmtHL._SX345_BO1,204,203,200_.jpg', 8.9, 9);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Trono de vidro', 31.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'A magia há muito abandonou Adarlan. Um perverso rei governa, punindo impiedosamente as minorias rebeldesAos 18 anos uma prisioneira está cumprindo sua sentença. Ela é uma assassina, e a melhor de Adarlan. Aprisionada e fraca, ela está quase perdendo as esperanças, a sentença de morte é iminente, mas a jovem recebe uma proposta inesperada: representar o príncipe em uma competição com lutando contra os mais habilidosos assassinos e larápios do reino. Mas ela não diz sim apenas para matar, seu foco é obter sua liberdade de volta.Se derrotar os 23 assassinos, ladrões e soldados, será a campeã do rei e estará livre depois de servi-lo por alguns anos.Endovier é uma sentença de morte, e cada duelo em Adarlan será para viver ou morrer. Mas se o preço é ser livre, e ela está disposta a tudo.Seu nome é Celaena Sardothien. O príncipe herdeiro vai provocá-la, o capitão da guarda fará tudo para protegê-la. E uma princesa de terras distantes se tornará algo que Celaena jamais pensou ter novamente: uma amiga.Mas algo maligno habita o castelo - e está ali para matar. Quando os demais competidores começam a morrer, um a um e de maneira terrível, Celaena se vê mais uma vez envolvida em uma batalha pela sobrevivência e inicia uma jornada desesperada para desvendar a origem daquele mal antes que ele destrua o mundo dela. E sua única chance de ser livre.No ritmo dos livros de fantasia de Tolkien, o mundo de Celaena é aquele em que a magia é proibida e o poder é arrebatado pela ganância. A narrativa em terceira pessoa permite uma visão frequente de vários personagens (heróis e vilões), mas sem perder o foco da confiante e conflitante protagonista.Eleito um dos melhores livros do ano pela Amazon e best seller do New York Times, o universo de Trono de vidro começou a ganhar forma quando Sarah J. Maas pensou: e se Cinderela fosse uma assassina? E se fosse ao baile não para dançar com o príncipe, mas para matá-lo? Assim nasceu Celaena Sardothien, a heroína que conquistou milhares de leitores por todo o mundo.', 'https://images-na.ssl-images-amazon.com/images/I/41rtnHT5SsL._SX335_BO1,204,203,200_.jpg', 7);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Corte de espinhos e rosas', 31.80, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Ela roubou uma vida. Agora deve pagar com o coração. Corte de espinhos e rosas é primeiro volume da série best-seller, da mesma autora da saga Trono de vidro. Num mundo dividido uma muralha mágica separa duas espécies. De um lado, os feéricos vivem dentro de suas fronteiras cheias de beleza e mistério; do outro, os humanos possuem apenas medo, desconfiança e dificuldades.Feyre, filha de um casal de mercadores humanos e falidos, se torna caçadora para sustentar a família. Dura como as flechas que carrega, letal como sua pontaria, ela abandona as fantasias de garota e as troca pela árdua vida nas florestas ao redor de sua aldeia.Sua única alegria é observar as cores e sonhar em capturá-las. Mas, na floresta, coberta de neve tudo é branco e árido; como o ódio pelos feéricos que carrega no coração; Como as telas que não pode comprar ou colorir. Até que um enorme lobo cruza seu caminho... Sem hesitar, Feyre dispara... uma flecha. Um ato de rebelião.Após matar o lobo, uma criatura bestial surge exigindo uma reparação. Arrastada para além do muro, para uma terra mágica e traiçoeira - que ela só conhece por meio de lendas -, a jovem descobre que seu captor não é um animal, mas Tamlin, Grão Senhor da Terra Primaveril. Um feérico com um segredo, escondido sob uma máscara. Ela descobre ainda que o então animal que havia assassinado era, na verdade, uma criatura mágica, uma fada zoomórfica transformada em lobo.À medida que ela descobre mais sobre este mundo onde a magia impera, seus sentimentos por Tamlin passam da mais pura hostilidade até uma paixão avassaladora. Enquanto isso, uma sinistra e antiga sombra avança sobre o mundo das fadas e Feyre deve provar seu amor para detê-la ou Tamlin e seu povo estarão condenados.Corte de espinhos e rosas é um livro de fantasia de tirar o fôlego. Memorável em todos os aspectos, com personagens complexos, enredo rico e um magnífico mundo de fantasia combinados impecavelmente para criar um romance épico.', 'https://images-na.ssl-images-amazon.com/images/I/51uoc3WIqVL._SX335_BO1,204,203,200_.jpg', 8);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Corte de névoa e fúria', 39.00, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Corte de névoa e fúria é o esperado segundo volume da saga iniciada em Corte de espinhos e rosas, da mesma autora da série Trono de vidro. Neste livro, seguimos a saga de Feyre Archeron, que morreu Sob a Montanha. Nas garras de Amarantha, a jovem humana que ansiava por amor e proteção deixou de existir. Das cinzas de seu velho eu, Feyre Quebradora da Maldição foi Feita - com poderes de sete Grão-Feéricos... e uma vontade tão férrea quanto o metal temido por eles.Seu coração no entanto, permanece humano, vulnerável. Incapaz de esquecer o que sofreu para libertar o povo de Tamlin... e o pacto firmado com Rhysand, senhor da Corte Noturna. Mas mesmo assim, Feyre se esforça para reconstruir o lar que criou na Corte Primaveril. Então por que é ao lado de Rhys que ela se sente mais plena?Peça-chave num jogo que desconhece. Feyre deve aprender rapidamente do que á capaz. E curar sua alma partida. Pois um antigo mal, muito pior que Amarantha, se agita no horizonte... um que ameaça não apenas os feéricos, mas o mundo humano e a muralha também.Enquanto navega por uma teia de intrigas políticas, paixões e poder, sufocada por Tamlin, Feyre precisa decidir o que deseja: amor ou liberdade?Corte de névoa e fúria apresenta uma história de emoção absoluta. Feyre aprende como se tornar uma verdadeira guerreira usando as ferramentas que possui. Um novo elenco de personagens dá vida ao reino. Cassian e Azriel - os irmãos de armas de Rhys, o sempre poderoso e charmoso Morrigan e o mortal, sarcástico, Amren.Sarah J. Maas desenvolve a narrativa com tramas tão hábeis que nenhum leitor pode começar este livro sem tentar terminá-lo o mais rápido possível. É cativante, romântico, cheio de ação e um estudo intenso dos reinos em guerra. Um verdadeiro clássico no gênero fantasia.', 'https://images-na.ssl-images-amazon.com/images/I/51-84mU8m0L._SX334_BO1,204,203,200_.jpg', 10);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Corte de asas e ruína', 45.99, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Corte de asas e ruína é o terceiro volume da série best-seller Corte de Espinhos e Rosas, da mesma autora da saga Trono de vidro. Seguindo os acontecimentos do volume anterior, Corte de névoa e fúria, acompanhamos a saga de Feyre Archeon, que suportou a fome, o frio e a desesperança, atravessou a Montanha e foi Sob a Montanha. Reclamou seu amor, quebrou a maldição e livrou o povo feérico da mais terrível ameaça... ou não? Amarantha pode ter sido aniquilada, mas o rei de Hybern pretende usar o Caldeirão para moldar um novo tempo; uma época de trevas e escravidão.A guerra se aproxima, um conflito que promete devastar Prythian. Em meio à Corte Primaveril, num perigoso jogo de intrigas e mentiras, a Grã-Senhora da Corte Noturna esconde seu laço de parceria e sua verdadeira lealdade. Longe de sua corte, longe de seu Grão-Senhor e verdadeiro amor, ela reúne informações, na esperança de vencer Hybern.Tamlin está fazendo acordos com o invasor, Jurian recuperou suas forças e as rainhas humanas prometem se alinhar aos desejos de Hybern em troca de imortalidade. O exército inimigo parece imbatível. Mas o sonho de Velaris é como um farol em meio às trevas. O ideal de um mundo mais justoEnquanto isso Feyre e seus amigos precisam aprender em quais Grãos-Senhores confiar, e procurar aliados nos mais improváveis lugares. Porém, a Quebradora da Maldição ainda tem uma ou duas cartas na manga antes que sua ilha queime.Sarah J. Maas faz questão de salientar neste livro que Rhysand e Feyre são iguais. A protagonista não é retratada como uma donzela fraca em perigo, ela realmente é uma guerreira forte e determinada! Os personagens são muito complexos, todas as perguntas que permeiam a trama serão respondidas. Corte de asas e ruína é um romance épico que preenche todos os requisitos para um livro exemplar, abrindo caminho de forma impecável para o final de uma série inesquecível.', 'https://images-na.ssl-images-amazon.com/images/I/61vIfK0qQgL._SX334_BO1,204,203,200_.jpg', 3.3);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('O Ladrão de Raios', 31.88, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Em O ladrão de raios, Percy Jackson, o menino que aos doze anos descobre que é um semideus, filho de Poseidon, precisa impedir uma guerra entre os deuses que destruiria a civilização ocidental; em O Mar de Monstros, ele e os amigos se envolvem em uma perigosa aventura para defender o acampamento dos semideuses; em A maldição do titã, Percy descobre que o Senhor dos Titãs despertou e está disposto a destruir a humanidade; em A batalha do Labirinto, o semideus vai combater o perigoso titã no temido Labirinto de Dédalo; e em O último olimpiano, Percy tem que lidar não só com o exército de Cronos, mas também com a chegada de seu décimo sexto aniversário — e, assim, com a profecia que determinará seu destino.', 'https://m.media-amazon.com/images/P/B009M84O0S.01._SCLZZZZZZZ_SX500_.jpg', 6.7);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('O mar de monstros', 18.66, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', ' Nessa nova aventura, Percy e seus amigos estão em busca do Velocino de Ouro, único artefato mágico capaz de proteger da destruição seu lugar predileto e, até então, o mais seguro do mundo: o Acampamento Meio-Sangue. Com o envenenamento da árvore de Thalia por um inimigo misterioso, as fronteiras mágicas que protegem o Acampamento estão ameaçadas, e é preciso buscar o antídoto. Assim, nossos heróis partem em uma arriscada e incrível viagem pelo Mar de Monstros, localizado nas coordenadas 30-31-75-12: uma referência ao Triângulo das Bermudas. Lá, enfrentam seres fantásticos e muitos perigos e situações inusitadas, que põem à prova seu heroísmo e sua herança – quando Percy irá questionar se ser filho de Poseidon é uma honra ou uma terrível maldição. Combinando fatos contemporâneos com mitologia, fantasia com erudição, O Mar de Monstros diverte, encanta e ensina pais e filhos.', 'https://m.media-amazon.com/images/I/51PiA-09C+L.jpg', 9.3);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('A Maldição do Titã', 20.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Percy descobre que o Senhor dos Titãs despertou e está disposto a destruir a humanidade', 'https://images-na.ssl-images-amazon.com/images/I/51FlbodO3qL._SX331_BO1,204,203,200_.jpg', 8.8);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('A Batalha do Labirinto', 32.19, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'O semideus vai combater o perigoso titã no temido Labirinto de Dédalo; e em O último olimpiano, Percy tem que lidar não só com o exército de Cronos, mas também com a chegada de seu décimo sexto aniversário — e, assim, com a profecia que determinará seu destino.', 'https://images-na.ssl-images-amazon.com/images/I/51QO+kd+8PL._SX323_BO1,204,203,200_.jpg',9);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('O último olimpiano', 21.45, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Os meios-sangues passaram o ano inteiro preparando-se para a batalha contra os Titãs, e sabem que as chances de vitória são pequenas. O exército de Cronos está mais poderoso que nunca, e cada novo deus ou semideus que se une à causa confere mais força ao vingativo titã. Enquanto os Olimpianos se ocupam de conter a fúria do monstro Tifão, Cronos avança em direção à cidade de Nova York, onde o Monte Olimpo está precariamente vigiado. Agora, apenas Percy Jackson e seu exército de heróis podem deter o Senhor do Tempo. Nesse quinto e último livro da série, o combate se acirra e o mundo que conhecemos está prestes a ser destruído. O destino da civilização está nas mãos do semideus anunciado na antiga profecia, e Percy está perto de completar dezesseis anos – a dúvida é: o herói será ou não capaz de tomar a decisão correta?', 'https://m.media-amazon.com/images/I/515u5OKYL0L.jpg', 8.9);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('O Herói Perdido', 28.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Depois de salvar o Olimpo do maligno titã Cronos, Percy Jackson e seus amigos trabalharam duro para reconstruir seu mais querido refúgio, o Acampamento Meio-Sangue. É lá que a próxima geração de semideuses terá de se preparar para enfrentar uma nova e aterrorizante profecia. Os campistas seguirão firmes na inevitável jornada, mas, para sobreviver, precisarão contar com a ajuda de alguns heróis, digamos, um pouco mais experientes - semideuses dos quais todos já ouvimos falar... e muito.', 'https://images-na.ssl-images-amazon.com/images/I/51q24M7HYuL._SX346_BO1,204,203,200_.jpg', 7.5);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('O Filho de Netuno', 29.89, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Com início no “outro” acampamento meio-sangue e se estendendo para além das terras dos deuses, esta sequência da série Os heróis do Olimpo apresenta novos semideuses e criaturas incríveis, além de trazer de volta alguns monstros bastante conhecidos.', 'https://images-na.ssl-images-amazon.com/images/I/51jnmaFSDSL._SY498_BO1,204,203,200_.jpg', 5.5);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Apple MacBook Pro 13"', 10064.39, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Apple MacBook Pro 13", Chip M1, 8GB RAM, 256GB SSD - Space Gray', 'https://m.media-amazon.com/images/I/81zKcC5wJ6L._AC_SL1500_.jpg',4.8);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Apple iPhone 13 Pro Max', 11565.00, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Apple iPhone 13 Pro Max 128gb Grafite MLTP3LL/A', 'https://m.media-amazon.com/images/I/61IJBsHm97L._AC_SL1500_.jpg', 8.6);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Jogo War Grow', 89.99, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Jogo War O melhor jogo de estratégia de todos os tempos! Com War, uma batalha nunca é igual a outra, e cada jogador precisa usar toda sua habilidade militar para conquistar territórios e continentes e derrotar seus adversários. Sinta-se no papel de um verdadeiro general. Sorteie seu objetivo e defina a sua estratégia. Ataque na hora certa, defenda seus territórios e proteja suas fronteiras. Domine continentes inteiros, invada e conquiste os territórios adversários. Mas conheça bem o poder de suas tropas, pois, assim como nas grandes guerras, ataques mal planejados podem fazer grandes potências cair, enquanto exércitos menores podem virar poderosos impérios se usarem a estratégia certa.', 'https://m.media-amazon.com/images/I/61b7dfGwn-L._AC_SL1200_.jpg', 9);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Mansions of Madness', 329.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Defina um campo para o terror não contado com a expansão de luxo das horríveis jornadas para Mansions of Madness: segunda edição! Uma nova equipe de investigadores corre para resolver mistérios perigosos à medida que enfrentam perigo cada vez maior. Quanto mais eles andam de casa. Com novos monstros, mistérios e eventos Mythos, para chegar ao seu destino, você deve primeiro sobreviver à jornada!', 'https://m.media-amazon.com/images/I/711Y5ZVWD8L._AC_SL1200_.jpg', 4.2);
INSERT INTO tb_product (name, price, date, description, img_url, rate_average) VALUES ('Jogo Banco Imobiliário', 85.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'O mercado de imóveis se modernizou e está cada vez mais competitivo. Diversificar os investimentos virou palavra de ordem. O banco imobiliário traz todo o dinamismo do mundo dos negócios para os dias de hoje.', 'https://m.media-amazon.com/images/I/910QO41sGRL._AC_SL1500_.jpg', 5.5);


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);